{"created": 1742323857.742306, "duration": 0.45455098152160645, "exitcode": 2, "root": "/Users/fsiqueira/Desktop/GitHub/omega-btc-ai", "environment": {}, "summary": {"total": 0, "collected": 0}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "omega_ai/tests/mm_trap_detector/test_mm_trap_processor.py", "type": "Module"}]}, {"nodeid": "omega_ai/tests/mm_trap_detector/test_mm_trap_processor.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module '/Users/fsiqueira/Desktop/GitHub/omega-btc-ai/omega_ai/tests/mm_trap_detector/test_mm_trap_processor.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n../../../.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/_pytest/python.py:493: in importtestmodule\n    mod = import_path(\n../../../.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/_pytest/pathlib.py:587: in import_path\n    importlib.import_module(module_name)\n/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py:88: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1387: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1360: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:935: in _load_unlocked\n    ???\n../../../.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:185: in exec_module\n    exec(co, module.__dict__)\nomega_ai/tests/mm_trap_detector/test_mm_trap_processor.py:19: in <module>\n    from omega_ai.tests.mm_trap_detector.test_helpers import _run_detector_once\n../../../.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:185: in exec_module\n    exec(co, module.__dict__)\nomega_ai/tests/mm_trap_detector/test_helpers.py:2: in <module>\n    from omega_ai.mm_trap_detector.mm_trap_processor import process_mm_trap\nE   ImportError: cannot import name 'process_mm_trap' from 'omega_ai.mm_trap_detector.mm_trap_processor' (/Users/fsiqueira/Desktop/GitHub/omega-btc-ai/omega_ai/mm_trap_detector/mm_trap_processor.py)"}], "tests": [], "warnings": [{"message": "Unknown config option: markers +\n", "category": "PytestConfigWarning", "when": "config", "filename": "/Users/fsiqueira/.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/_pytest/config/__init__.py", "lineno": 1441}, {"message": "datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).", "category": "DeprecationWarning", "when": "collect", "filename": "/Users/fsiqueira/.local/share/virtualenvs/omega-btc-ai-Me3wBGdS/lib/python3.13/site-packages/reactivex/internal/constants.py", "lineno": 4}]}